import { useState } from 'react';
import { INITIAL_QUEUE } from '../data/content';

export default function PanchayatCopilot({ pushToast }) {
  const [queue, setQueue] = useState(
    [...INITIAL_QUEUE].sort((a, b) => b.urgency - a.urgency)
  );
  const [selected, setSelected] = useState(null);
  const [draft, setDraft] = useState('');
  const [handover, setHandover] = useState(null);

  const backlog = queue.filter((q) => q.status !== 'Resolved').length;
  const overloaded = backlog >= 4;

  function openDraft(item) {
    setSelected(item);
    setDraft(
      `Dear ${item.citizen},\n\nRegarding your request "${item.type}" (Ref: ${item.id}):\nBased on similar precedent cases, the recommended next step is to verify submitted documents and forward to the concerned department within 48 hours.\n\n— Auto-drafted by Sahayak Copilot, please review & edit before sending.`
    );
  }

  function approve(id) {
    setQueue((prev) => prev.map((q) => (q.id === id ? { ...q, status: 'Resolved' } : q)));
    pushToast(`✅ Response approved & sent for ${id}`);
    setSelected(null);
  }

  function generateHandover() {
    setHandover(
      `HANDOVER BRIEF — Panchayat Secretary Role\n\nGenerated by Sahayak Institutional Memory Engine\n\n• 42 pension cases resolved this quarter — common blocker: missing death/age certificates → recommend proactive CSC referral.\n• Water complaints spike during March–May; escalate to Block Engineer directly, skip intermediate review.\n• Recurring contact: District Welfare Officer (for PM-KISAN discrepancies) — direct line preferred over email.\n• 3 habitual SLA-breach categories flagged for successor's priority queue.`
    );
    pushToast('📄 Handover brief generated for successor officer');
  }

  return (
    <div className="view fade-in">
      <section className="card">
        <span className="badge badge-blue">Phase 2 · Roadmap Preview</span>
        <h2>🧑‍💼 Panchayat Copilot</h2>
        <p className="note">
          "What happens when 10,000 Ramesh Devis use this at once?" — This is the system-side answer:
          an AI co-pilot for the official, not just a chatbot for the citizen.
        </p>
      </section>

      {overloaded && (
        <div className="alert-banner">
          🚨 Officer Load-Balancing Alert: Backlog ({backlog} open cases) has crossed threshold. District admin
          notified to redistribute cases / deploy temporary support.
        </div>
      )}

      <section className="card">
        <h3>📊 Priority Triage Dashboard</h3>
        <table className="queue-table">
          <thead>
            <tr><th>ID</th><th>Citizen</th><th>Type</th><th>Urgency</th><th>Status</th><th></th></tr>
          </thead>
          <tbody>
            {queue.map((q) => (
              <tr key={q.id} className={q.slaBreach && q.status !== 'Resolved' ? 'row-danger' : ''}>
                <td>{q.id}</td>
                <td>{q.citizen}</td>
                <td>{q.type}</td>
                <td>
                  <div className="urgency-bar">
                    <div className="urgency-fill" style={{ width: `${q.urgency}%` }} />
                  </div>
                </td>
                <td><span className={`tag ${q.status === 'Resolved' ? 'tag-ok' : q.slaBreach ? 'tag-danger' : 'tag-warn'}`}>{q.status}</span></td>
                <td>
                  {q.status !== 'Resolved' && (
                    <button className="btn btn-ghost btn-sm" onClick={() => openDraft(q)}>Draft Response</button>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      {selected && (
        <section className="card">
          <h3>✍️ AI-Drafted Response Queue — {selected.id}</h3>
          <textarea rows={7} value={draft} onChange={(e) => setDraft(e.target.value)} />
          <div className="row-between">
            <button className="btn btn-ghost btn-sm" onClick={() => setSelected(null)}>Cancel</button>
            <button className="btn btn-primary btn-sm" onClick={() => approve(selected.id)}>✅ Approve & Send</button>
          </div>
        </section>
      )}

      <section className="card">
        <h3>🧠 Institutional Memory Transfer</h3>
        <p className="note">On transfer/retirement, Sahayak compiles decision patterns into a handover brief for the successor.</p>
        <button className="btn btn-primary btn-sm" onClick={generateHandover}>Generate Handover Brief</button>
        {handover && <pre className="rti-box">{handover}</pre>}
      </section>
    </div>
  );
}
